site_name: mxt的学习笔记
nav: 
  - 主页: index.md
  - 国外课程学习记录: 
    - AI相关:
      - Machine Learning: 'AI/ML/ML.md'
      - Machine Learning With Python: 'AI/ML/ML_with_py.md'
    - CS相关:
      - CS61A: 'CS/CS61A/CS61A学习笔记.md'
      - CS61B: 'CS/CS61B/project 2.md'
  - 自主学习:
    - DataWhale:
      - Leetcode: 'DataWhale/Leetcode/task1.md'
  - 一些工具的学习笔记:
    - Mathmetica:
      - Mathematica: 'CS/Tools/Mathematica/Mathematica.md'
      - Mathematica编程: 'CS/Tools/Mathematica/Mathe.md'
    - LaTex:
      - LaTex写作常见问题: 'CS/Tools/LaTex/Question.md'
      - LaTex常用的模板: 'CS/Tools/LaTex/Template.md'
  - 语言学习:
    - python学习相关:
      - py速成练习: 'Tutorial/py速成练习'
  - 小项目:
    - 二维码识别与网站打开: 'project/二维码识别与打开网站/project.md'
    - 人脸睡意检测: 'project/睡意检测/project.md'
  - lab:
    - 计算机网络: 
      - 第二次实验: 'lab/net/计算机网络第二次实验/计算机网络第二次实验报告.md'
      - 第三次实验: 'lab/net/计算机网络第三次实验/2023_4_26 计算机网络.md'
    - 数据库应用:
      - 第七章实验: 'lab/dbapp/第七章/2023_4_27实验报告.md'
  - 课程相关:
    - 计算机图形学:
      - 复习参考: 'leason/CG/test.md'
  - 杂项:
    - Java: 'Tutorial/Java.md'
    - 算法复习: 'Tutorial/算法复习计划.md'
    - 数据库: 'Tutorial/SQL.md'
    #- 数据库:
    #- other:
  - 关于我: about.md

#主题
theme:
  name: 'material'
  favicon: resources/img/logo.png
  language: 'zh'  # 配置语言
  palette:
    - primary: 'lingo'  #颜色
    - accent: 'Teal'
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font: #字体
    text: 'Ubuntu' 
    code: 'Ubuntu Mono'
  feature:
    tabs: true  # 横向导航
  custom_dir: 'docs/resources/'

markdown_extensions:

  # Python Markdown
  - abbr # 作用为解析缩写
  - admonition #作用为解析警告
  - attr_list #作用为解析属性列表
  - def_list #作用为解析定义列表
  - footnotes #作用为解析脚注
  - md_in_html #作用为解析html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js